
name: PDF Compile Action
on:
  #push:
  #  branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: add permissions
        run: "git config --global --add safe.directory /__w/Resume/Resume"
      - name: set git variables
        run: |
            git config --global user.email "sophia_campana.com"
            git config --global user.name "Sophia Campana"
      - name: cleanup old pdfs
        run: |
          git rm --ignore-unmatch *.pdf
          git commit --allow-empty -m 'removing old pdfs, github action'
          git push
      - name: Run latexmk
        run: "latexmk --pdflatex main.tex"
      - name: Store build timestamp
        run: echo "BUILD_TIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV
      - name: change file name
        run: "mv main.pdf main$BUILD_TIME.pdf"
      - name: adding new pdfs
        run: |
          git add main$BUILD_TIME.pdf
          git commit -m 'adding new pdfs, github action'
          git push
